version: "3.8"

services:
  mongo:
    image: mongo:8.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  stakeholders-service:
    build:
      context: ./stakeholders-service
      dockerfile: Dockerfile
    container_name: stakeholders-service
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=stakeholders
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=blogs
      - PORT=8081
    restart: unless-stopped

  neo4j:
    image: neo4j:5.10
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/testtest123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

  follower-service:
    build:
      context: ./follower-service
      dockerfile: Dockerfile
    container_name: follower-service
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=testtest123
    ports:
      - "8082:8082"
    restart: unless-stopped

  tour-service:
    build:
      context: ./tour-service
      dockerfile: Dockerfile
    container_name: tour-service
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=tours
    ports:
      - "8083:8083"
    restart: unless-stopped




volumes:
  mongo-data:
  neo4j-data: